---
title: "Songyi's Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(rio)
library(scales)
library(patchwork)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
gap <- import(here("data", "gapminder.csv")) %>% as_tibble()

continent_counts <- gap %>%
group_by(continent) %>%
summarize(num_countries = n_distinct(country))

ggplot(continent_counts, aes(x = continent, y = num_countries, fill = continent)) +
geom_col() +
scale_fill_viridis_d()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
gap2007 <- gap %>% filter(year == 2007)

ggplot(gap2007, aes(x = gdpPercap, y = lifeExp,
color = continent, shape = continent, size = pop)) +
geom_point() +
scale_x_log10(labels = label_dollar()) +
scale_color_viridis_d() +
scale_shape_manual(values = c(15, 16, 17, 18, 25)) +
scale_size_continuous(range = c(1, 7), labels = label_comma()) +
labs(
title = "GDP per Capita and Life Expectancy (2007)",
x = "GDP per Capita (log scale)",
y = "Life Expectancy",
color = "Continent",
shape = "Continent",
size = "Population"
) +
theme_minimal()
```

### Chart C

```{r}
gap2007american <- gap %>% filter(year == 2007 & continent == "Americas")

ggplot(gap2007american, aes(x = gdpPercap, y = lifeExp, size = pop, label = country)) +
  geom_point() +
  geom_text(vjust = -1.5, size = 2.5) +
  scale_x_log10(labels = label_dollar()) +
  scale_size_continuous(range = c(1, 7), labels = label_comma()) +
  labs(
    title = "GDP per Capita and Life Expectancy of American Continent Countries",
    x = "GDP per Capita (log scale)",
    y = "Life Expectancy",
    size = "Population") +
  theme_minimal()
```

